//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class RegisterPatientPanel extends JPanel {
    private JTextField FirstName;
    private JTextField ID;
    private JTextField EmergencyContactPhone;
    private JTextField Age;
    private JTextField PhoneNumber;
    private JTextField DateOfEntry;
    private JTextField LastName;
    private JTextField Email;
    private JTextField Profession;
    private JTextField Gender;
    private JLabel jcomp11;
    private JLabel jcomp12;
    private JLabel jcomp13;
    private JLabel jcomp14;
    private JLabel jcomp15;
    private JLabel jcomp16;
    private JLabel jcomp17;
    private JLabel jcomp18;
    private JLabel jcomp19;
    private JLabel jcomp20;
    private JButton Register;
    private JLabel Result;

    public RegisterPatientPanel() {
        //construct components
        FirstName = new JTextField (5);
        ID = new JTextField (5);
        EmergencyContactPhone = new JTextField (5);
        Age = new JTextField (5);
        PhoneNumber = new JTextField (5);
        DateOfEntry = new JTextField (5);
        LastName = new JTextField (5);
        Email = new JTextField (5);
        Profession = new JTextField (5);
        Gender = new JTextField (5);
        jcomp11 = new JLabel ("First Name");
        jcomp12 = new JLabel ("Last Name");
        jcomp13 = new JLabel ("Date of Entry");
        jcomp14 = new JLabel ("ID");
        jcomp15 = new JLabel ("Phone Number");
        jcomp16 = new JLabel ("Profession");
        jcomp17 = new JLabel ("Email");
        jcomp18 = new JLabel ("Age");
        jcomp19 = new JLabel ("Gender");
        jcomp20 = new JLabel ("Emergency Contact Phone");
        Register = new JButton ("Register");
        Result = new JLabel ("");

        //adjust size and set layout
        setPreferredSize (new Dimension (667, 366));
        setLayout (null);

        //add components
        add (FirstName);
        add (ID);
        add (EmergencyContactPhone);
        add (Age);
        add (PhoneNumber);
        add (DateOfEntry);
        add (LastName);
        add (Email);
        add (Profession);
        add (Gender);
        add (jcomp11);
        add (jcomp12);
        add (jcomp13);
        add (jcomp14);
        add (jcomp15);
        add (jcomp16);
        add (jcomp17);
        add (jcomp18);
        add (jcomp19);
        add (jcomp20);
        add (Register);
        add (Result);

        //set component bounds (only needed by Absolute Positioning)
        FirstName.setBounds (130, 35, 100, 25);
        ID.setBounds (130, 80, 100, 25);
        EmergencyContactPhone.setBounds (420, 125, 100, 25);
        Age.setBounds (130, 170, 100, 25);
        PhoneNumber.setBounds (130, 125, 100, 25);
        DateOfEntry.setBounds (420, 80, 100, 25);
        LastName.setBounds (420, 35, 100, 25);
        Email.setBounds (130, 215, 100, 25);
        Profession.setBounds (420, 215, 100, 25);
        Gender.setBounds (420, 170, 100, 25);
        jcomp11.setBounds (15, 35, 100, 25);
        jcomp12.setBounds (300, 35, 100, 25);
        jcomp13.setBounds (300, 80, 100, 25);
        jcomp14.setBounds (15, 75, 100, 25);
        jcomp15.setBounds (15, 125, 100, 25);
        jcomp16.setBounds (290, 215, 100, 25);
        jcomp17.setBounds (15, 215, 100, 25);
        jcomp18.setBounds (15, 170, 100, 25);
        jcomp19.setBounds (300, 170, 100, 25);
        jcomp20.setBounds (255, 125, 165, 25);
        Register.setBounds (245, 265, 155, 40);
        Result.setBounds (245, 320, 155, 35);
        
        
        Register.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            { 
          	String s = e.getActionCommand(); 
                if (s.equals("Register")) 
                { 
                	System.out.println(FirstName.getText());
                	
                }
              }
        });
    }
                


    public static void main (String[] args) {
        JFrame frame = new JFrame ("RegisterPatientPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new RegisterPatientPanel());
        frame.pack();
        frame.setVisible (true);
    }
    
}
